tsuru/tsuru-client

misc/zsh-completion

This is a very basic zsh-completion - for now it only complete the first level of commands, very similar to what `bash-completion` does.

Add script for ZSH completion

---

tsuru/auth.go
tsuru/auth_test.go

Don't delete `~/.tsuru-token` when deleting a user with `user-remove`. So
that an administrator deleting other users doesn't have to re-login after
each command.
I did think about retaining the existing behaviour for the "without args"
case where you are deleting yourself. However it ever so slightly increased
the code complexity and the test may have produced false-negatives in the
future, which didn't seem worth it when the user's token would be
invalidated and they'd be prompted to login the next time anyway.
Fixes tsuru/tsuru#1235

auth: Keep .tsuru-token on user-remove

---

Makefile

This Pull request removes a Makefile target rule that is no longer used

Manpages are now generated by Sphinx. Removing old target rule

---

tsuru/client/auth.go
tsuru/client/auth_test.go

When you execute 'tsuru token-show -u test+testing@example.com' the email argument wasn't encoded correctly as a query string parameter to the tsuru server.
As a result the tsuru server was getting "test testing@example.com" as the email value on this case.
Fixed that query string encoding on "token-show" and "user-remove" commands with this PR.
I also updated a "user-remove" test to show the problem (without these changes to auth.go, this updated test would fail).
This problem was introduced on: https://github.com/tsuru/tsuru/issues/1442 and it wasn't a problem in the email validation function itself, like i said on this PR to tsuru: https://github.com/tsuru/tsuru/pull/1461

fix tsuru issue #1442 - token-show and user-remove commands correct passing email argument

---

tsuru/admin/platform.go
tsuru/admin/pool.go

This PR update admin commands to use tsuru instead of tsuru-admin in command helpers.
Also to use ```node-add``` instead of ```docker-node-add```

Updates admin command helpers

---

tsuru/installer/dm/dockermachine.go
tsuru/installer/dm/dockermachine_test.go

Fix the following issue:
```
Uploading registry certificate...
Error: failed to provision components machines: failed to provision machines: error uploading registry certificates to 1.2.3.4: Something went wrong running an SSH command!
command : sudo mkdir /etc/docker/certs.d && sudo cp -r /home/docker-user/certs/* /etc/docker/certs.d/
err     : exit status 1
output  : mkdir: cannot create directory ‘/etc/docker/certs.d’: File exists
```

Add -p to mkdir

---

tsuru/installer/dm/drivers.go
tsuru/installer/dm/drivers_test.go

When using Google Cloud as driver for docker-machine, like with Amazon EC2, eth0 is the internal interface and must be forced to avoid some errors during the install
Fix https://github.com/tsuru/tsuru/issues/1505

Force eth0 as internal interface for Google Cloud

---

tsuru/client/pool.go
tsuru/client/pool_test.go

With empty pool-list
Before:
```
$ tsuru pool-list
Error: EOF
```
After:
```
$ tsuru pool-list
+------+------+-------------+-------+---------+
| Pool | Kind | Provisioner | Teams | Routers |
+------+------+-------------+-------+---------+
+------+------+-------------+-------+---------+
```

client: improve error handling in pool-list

---

tsuru/client/env.go
tsuru/client/env_test.go

support for multiline environment variables is not supported by default because regex and processing logic silently truncate in the first line

env: support for multiline environment variables

---

tsuru/client/volume.go
tsuru/client/volume_test.go

Prevents `Error: unexpected end of JSON input` on empty plan list.

client: properly handle empty plan list

---

tsuru/installer/components.go
tsuru/installer/compose.go
tsuru/installer/defaultconfig/compose.yml
tsuru/installer/defaultconfig/configs.go
tsuru/installer/install_test.go
tsuru/installer/installer.go
tsuru/installer/testdata/hosts.yml

This PR makes its easier to choose a particular tsuru api image and prevents having to generate a complete compose file just for this small and probably common configuration.

installer: enables customizing tsuru api image

---

tsuru/client/event.go
tsuru/client/event_test.go

Event cancellation is async so we can't tell if the event was really cancelled right after the cancellation was requested.

event: clarifies event cancellation message

---

tsuru/client/services.go
tsuru/client/services_test.go

tsuru/tsuru#1459 happens cause when the API responds to the request, It may send the error as well in the body, but It's mostly out of the first JSON sent on the Body, so variable `msgError` is always `nil`, what never causes the client to abort.
fixes tsuru/tsuru#1459

services: better client error handling

---

tsuru/client/deploy.go

This allows deploys to proceed even with broken symlinks.

client: no need to open symlink during app-deploy tar generation

---

Gopkg.lock
Gopkg.toml
vendor/github.com/Nvveen/Gotty/gotty.go

Issue https://github.com/tsuru/tsuru/issues/1936
This PR overrides Gotty docker dependence, 
using the fork: https://github.com/ijc/Gotty 
that implemented the PR: https://github.com/Nvveen/Gotty/pull/1
as made by docker: https://github.com/moby/moby/blob/17bb1d3663f6586e83b453670526e3186bb56dd3/vendor.conf#L141:12

vendor: override Gotty to fix array out-of-bounds access panic

---

tsuru/client/plugin.go
tsuru/client/plugin_test.go

The client will run a plugin if exactly 1 plugin file exists matching
the pattern `<plugin name>.<any extension>`.
This allows windows users to install a plugin as `file.exe` and then
call it with `tsuru file <args>`.

client: improve plugin experience on windows when plugin has extension

---

misc/bash-completion

An example of the new behavior for the bash completion:
```
$ tsuru app r<TAB><TAB>
remove   restart  revoke   router   routes   run
$ tsuru app router <TAB><TAB>
add     list    remove  update
$ tsuru <TAB><TAB>
app          cname        event        key          permission   reset        target       version
bs           container    healing      login        plan         role         team         volume
certificate  containers   help         logout       platform     router       token
change       docker       init         machine      plugin       service      unit
cluster      env          install      node         pool         tag          user
$ tsuru ap<TAB>
$ tsuru app<TAB><TAB>
app                         app-grant                   app-revoke                  app-start …
```

misc: autocomplete commands with space separator

---

Gopkg.lock
tsuru/client/auth.go
vendor/github.com/tsuru/go-tsuruclient/pkg/tsuru/api_client.go

This change uses the new added error type in go-tsuruclient
to refactor the way we parse errors from the library.

Refactor error parsing from go-tsuruclient

---

.dockerignore
Dockerfile

Currently, the `tsuru/client` image isn't building as expected on Docker Hub, see the last builds history. I think that's is related with absence of `musl-dev` package on the system, as mentioned on [this issue](https://github.com/docker-library/golang/issues/86).
In this PR, besides fixing the build I also updated the Alpine to its last version. :)

Fix tsuru-client's build on Docker image

---

tsuru/client/services.go
tsuru/client/services_test.go
tsuru/main.go
tsuru/main_test.go

This PR deprecates the tsuru client service-instance-status command in favor of the service-instance-info command.  The service-instance-info command now also checks the status of the given service instance.
See https://github.com/tsuru/tsuru/issues/2167 for details.
@ggarnier for comments.

Merge `service-instance-info` and `service-instance-status` commands

---

docs/source/reference.rst
tsuru/client/apps.go
tsuru/client/apps_test.go
tsuru/main.go
tsuru/main_test.go

Usage:
```
$ tsuru unit-set web 10 -a my-app
$ tsuru unit-set worker 2 -a my-app
```
This is just a convenience command over `unit-add` and `unit-remove`.
The idea is to allow more easily to adjust the desired number of units for each process, without having to calculate how many units have to be added or removed to achieve that.
I've tried to build the docs but `make doc` would keep failing because of other commands and I didn't know how to fix it.

Add `unit-set` command

---

Gopkg.lock
tsuru/admin/cluster.go
vendor/github.com/tsuru/go-tsuruclient/pkg/tsuru/api_app.go
vendor/github.com/tsuru/go-tsuruclient/pkg/tsuru/api_auth.go
vendor/github.com/tsuru/go-tsuruclient/pkg/tsuru/api_cluster.go
vendor/github.com/tsuru/go-tsuruclient/pkg/tsuru/api_event.go
vendor/github.com/tsuru/go-tsuruclient/pkg/tsuru/api_node.go
vendor/github.com/tsuru/go-tsuruclient/pkg/tsuru/api_platform.go
vendor/github.com/tsuru/go-tsuruclient/pkg/tsuru/api_pool.go
vendor/github.com/tsuru/go-tsuruclient/pkg/tsuru/api_service.go
vendor/github.com/tsuru/go-tsuruclient/pkg/tsuru/api_team.go
vendor/github.com/tsuru/go-tsuruclient/pkg/tsuru/api_user.go
vendor/github.com/tsuru/go-tsuruclient/pkg/tsuru/api_volume.go

The go-tsuruclient was also updated to send Accept headers and to stop it from reading the body if no response type is specified.

Stream response in cluster operations

---

tsuru/installer/compose.go
tsuru/installer/dm/drivers.go

Boot2docker image does not include base64 so we now fallback to either
openssl or python to do base64 decoding.
Fixes tsuru/tsuru#2279

installer: try multiple ways of decoding base64 data

---

go.mod
go.sum
tsuru/client/apps.go
tsuru/client/apps_test.go
tsuru/client/metadata.go
tsuru/client/metadata_test.go

Adds support for managing labels and annotations with the following commands:
- *app-metadata-get*
- *app-metadata-set*
- *app-metadata-unset*

feat: add app-metadata-{get/set/unset}

---

tsuru/installer/compose.go

Replace the command `sudo docker deploy  -c /etc/tsuru/compose.yml tsuru`
by `sudo docker stack deploy -c /etc/tsuru/compose.yml tsuru`.

docker: 'deploy' is not a docker command

---

tsuru/config/config.go
tsuru/config/config_test.go
tsuru/config/filesystem.go
tsuru/config/filesystem_test.go
tsuru/config/suite_test.go
tsuru/main.go

Implementing base structure for storing state
```json
{
"SchemaVersion": "0.1",
"LastUpdate": "2020-12-25T16:00:59Z"
}
```
It shall be extended to something like this (format is still work in progress)
```json
{
"SchemaVersion": "0.1",
"LastUpdate": "2020-12-25T16:00:59Z",
"AutoUpdate": {
"LastCheck": "2020-12-25T16:00:59Z",
"SnoozeUntil": "2025-12-25T16:00:59Z"
},
"plugins" : {
"bundles": [
"https://example.com/tsuru-plugin-bundle-1",
"https://example.com/tsuru-plugin-bundle-2"
]
} 
}
```
closes #170

add support for configs (offline state)

---

.dockerignore
Dockerfile
Makefile
goreleaser-rc.yml
goreleaser-stable.yml
tsuru/main.go

Ensure consistent version, by injecting the version at build time.
The version is derived from the latest git tag.
Goreleaser is responsible for deriving it (during CI).
If built with `make build`, the version is from `git describe --tags`, which should be the same string if build the latest tag.
This also give us reproducible builds (in theory). 
To test it, run this from the latest tag (only after this commit is merged and published)
```
goreleaser release --config goreleaser-stable.yml --skip-publish --rm-dist --auto-snapshot
md5sum $(which tsuru) ./dist/tsuru_$(uname -s | awk '{print tolower($0)}')_$(uname -m)*/tsuru
```

inject version at build time

---

tsuru/client/plugin.go
tsuru/client/plugin_test.go

Closes #172
This PR aims to introduce support for os/architecture agnostic manifest URL for plugin installation. It will utilize the GOOS and GOARCH variables in order to find the correspondent URL in order to download the plugin.
It also utilizes the Content-Type from the response in order to identify if it's a manifest file or an actual binary. Also added a validation to avoid infinite recursive calls.
Unsure if this implementation works with plugin bundle install, but believe it would.
Added a single unit test for a plugin install utilizing manifest file, feel free to suggest new cases to test, wanted to get a first input beforehand :)

feat: adding support for os/arch agnostic manifest url for plugin install

---

tsuru/client/archiver.go
tsuru/client/archiver_test.go
tsuru/client/archiver_unix_test.go
tsuru/client/build.go
tsuru/client/build_test.go
tsuru/client/deploy.go
tsuru/client/deploy_test.go
tsuru/client/suite_test.go
tsuru/client/testdata/deploy4/Dockerfile
tsuru/client/testdata/deploy4/app.sh

This PR implements the changes required to support deploy with Dockerfile (and files). 
Significant changes:
* Adds a new parameter `--dockerfile` on `tsuru app-deploy`;
* Changes the default compression level to best (9) - more CPU usage during the deploy/build;
* Rewrites the command description of `tsuru app-deploy` and `tsuru app-build`;
* Shows more info messages while compressing files to `archive.tar.gz`;

feat(app-deploy): support deploy with dockerfile

---

tsuru/client/deploy_test.go
tsuru/client/testdata/deploy4/Dockerfile

Hi!
The Dockerfile placed at "tsuru/client/testdata/deploy4/Dockerfile" contains the best practice violation [DL3007](https://github.com/hadolint/hadolint/wiki/DL3007) detected by the [hadolint](https://github.com/hadolint/hadolint) tool.
The smell DL3007 occurs when the tag "latest" is used instead of a specific version tag for the base image.
In this pull request, we propose a fix for that smell generated by our fixing tool. We have verified that the patch is correct before opening the pull request.
To fix this smell, specifically, we use a heuristic approach that selects the most probable version tag for the base image in order to replace the "latest" tag. In detail, it selects the most recent image tag which corresponds to the same image digest that currently corresponds to the …

Fix for Dockerfile smell DL3007

---

README.md
plugins.md

Documentation about plugins, what they are and how to create new plugins
Check how this gets rendered:
- https://github.com/tcarreira/tsuru-client/tree/master-doc-tsuru-plugins#tsuru-plugins
- https://github.com/tcarreira/tsuru-client/blob/master-doc-tsuru-plugins/plugins.md
closes: https://github.com/tsuru/tsuru-client/issues/192

docs: add Developing Tsuru Plugins

---

go.mod
go.sum
tsuru/admin/cluster.go
tsuru/client/apps.go
tsuru/client/deploy.go

Using the `tsuru-client` sometimes we can't see the confirmation input before entering the answer.
How to reproduce:
```sh
$ tsuru app remove -a gvicentin-static
Are you sure you want to remove app "gvicentin-static"? (y/n) n
Abort.
$ tsuru service instance remove rpaasv2-be gvicentin-be
n
Are you sure you want to remove the instance "gvicentin-be"? (y/n) Abort.
````
Since every confirmation input should not use pagination, we can call the RawOutput function to fix this weird behaviour. 
Dependency PR: https://github.com/tsuru/tsuru/pull/2693

bugfix: Missing confirmation input message

---

tsuru/client/services.go
tsuru/client/services_test.go

The tsuru-client can now use the tsuru API's tag filtering feature for services instances. The "tsuru service list" command now supports the -g or --tag flags like `tsuru service list -g key=value`. I based this improvement on the way tsuru-client does the `tsuru app list` command.

feat: Add --tag flag to filter services in tsuru service list

---

tsuru/admin/pool.go

Update tsuru client for the fix of [PR #2747](https://github.com/tsuru/tsuru/pull/2747) of Tsuru API

Fix: Cert issuer validation for apps
