tsuru/apps.go, tsuru/apps_test.go
https://github.com/tsuru/tsuru/issues/1106
@fsouza Could you please review this PR? If I understood you correctly that's it, right?
=> cmd/tsuru: app-remove should not guess the name of the app #1106

tsuru/env.go, tsuru/env_test.go
now client can set private variables
=> Added --private flag to set private environment variables

CONTRIBUTING.md
just copying the CONTRIBUTING.md file from https://github.com/tsuru/tsuru
It will help new developers and contributors with a start point.
=> CONTRIBUTING.md file

tsuru/apps.go, tsuru/apps_test.go
Fix the error message after "tsuru app-update" without -a argument.
=> fix error message

tsuru/client/run.go, tsuru/client/run_test.go
This PR implements the --isolated flag to app-run that execute a command in an ephemeral container.
=> Implementes app-run --isolated flag

tsuru/admin/iaas.go, tsuru/admin/iaas_test.go
=> Iaas temp update

tsuru/client/deploy.go, tsuru/client/deploy_test.go, tsuru/main.go
This PR is related to https://github.com/tsuru/tsuru/issues/1498 
and needs https://github.com/tsuru/tsuru/pull/1548 to be merged.
=> client: add app-deploy-rebuild cmd

docs/cmds.json, docs/source/reference.rst, tsuru/client/services.go, tsuru/client/services_test.go
Add support to manage tags in service instances. References tsuru/tsuru#1550
=> Service instance tags

docs/cmds.json, tsuru/client/apps.go, tsuru/client/apps_test.go
=> adds support for image-reset on next deploy by using app-update

docs/cmds.json, tsuru/admin/event.go, tsuru/admin/event_test.go, tsuru/client/permission.go, tsuru/client/permission_test.go, tsuru/client/services.go
=> Role update

tsuru/client/apps.go, tsuru/client/apps_test.go
=> App create without platform

tsuru/admin/pool.go
related to tsuru/tsuru/pull/1654
=> pool: docs to allow restricting services to certain pools

tsuru/client/deploy.go, tsuru/client/deploy_test.go, tsuru/main.go, tsuru/main_test.go
=> client: adds app-deploy-rollback-update

README.md
Really simple modification. Fixing README.
=> fixing README

docs/cmds.json, tsuru/client/services.go, tsuru/client/services_test.go
=> client: add team-owner parameter to service-instance-update

docs/cmds.json, tsuru/client/permission_test.go, tsuru/client/services.go, tsuru/client/services_test.go
Add plan parameter to `service-instance-update` command
=> Service instance update plan

docs/source/reference.rst, tsuru/admin/cluster.go, tsuru/admin/cluster_test.go
Added the confirmation dialog, as well as the command info hint and documentation entry. 
https://github.com/tsuru/tsuru/issues/1777
=> client: cluster-remove should ask for confirmation #1777

tsuru/client/deploy.go, tsuru/client/deploy_test.go
This continues the work started in #42 by extending the behavior of app-deploy --files-only to directory arguments.
It also unifies related tests and add more test cases for app-deploy tarball generation. This makes it simpler to see the intended behavior when -f flag is used.
See https://github.com/tsuru/tsuru-client/pull/71/files#diff-6afea40d566b360ea32f8a7024637827R612 for an example of how -f behaves when used with directories as arguments.
=> app-deploy: implement -f behavior for directories and more tests

tsuru/client/certificate.go, tsuru/client/certificate_test.go
Changed from map[string]string to map[string]map[string]string. 
Tsuru ref: https://github.com/tsuru/tsuru/commit/8a141690a3bd4278b0592aa7e75cab7d69d85ab8
=> Adding multiples routers per application broke the certificatelist

tsuru/client/services.go, tsuru/client/services_test.go
This PR adds default and required service broker plans on the
plan table.
=> service: display default and required plan parameter values

Gopkg.lock, tsuru/client/auth.go, tsuru/client/auth_test.go, tsuru/installer/components_test.go, vendor/github.com/tsuru/go-tsuruclient/pkg/tsuru/team.go, vendor/github.com/tsuru/go-tsuruclient/pkg/tsuru/team_data.go, vendor/github.com/tsuru/go-tsuruclient/pkg/tsuru/team_info.go, vendor/github.com/tsuru/go-tsuruclient/pkg/tsuru/update_data.go
This PR adds support for team tags in team commands.
=> Adds team tags to team cmds

tsuru/client/services.go, tsuru/client/services_test.go
This PR just adds some identation on the service instance
custom information
=> client: ident custom service information

CONTRIBUTORS, Gopkg.lock, Gopkg.toml, tsuru/installer/install_test.go, tsuru/installer/installer.go, tsuru/installer/installer_test.go, vendor/github.com/sethvargo/go-password/LICENSE, vendor/github.com/sethvargo/go-password/password/generate.go
Before this PR, the password of root user was hardcoded as "admin123", now it's generated on every time is called.
=> Generate pseudorandom password to root user on Tsuru installer

tsuru/admin/quota.go, tsuru/admin/quota_test.go
This PR get the app name from flags `-a` or `--app` on commands `app-quota-change` and `app-quota-view`.
Resolves https://github.com/tsuru/tsuru/issues/1624
=> Receive app name by parameter instead command

tsuru/installer/compose_test.go
I included some tests for the function `resolveConfig`.
=> Installer composer test

tsuru/client/deploy.go
This removes bufio.Scanner as it could fail when lines were too large with
ErrTooLong.
=> app-deploy: use fixed size buffer to write output instead of scanner

Gopkg.lock, tsuru/installer/compose.go, tsuru/installer/dm/drivers.go, tsuru/installer/dm/drivers_test.go, tsuru/installer/installer.go, vendor/github.com/docker/machine/drivers/azure/azureutil/azureutil.go, vendor/github.com/docker/machine/drivers/azure/azureutil/cleanup.go
This fixes issues with special characters in file contents breaking the installer.
Also this PR updates the vendored docker machine with some azure fixes.
=> installer: encode files as base64 before uploading to servers

tsuru/admin/iaas.go, tsuru/admin/iaas_test.go
Related to https://github.com/tsuru/tsuru/issues/2267
=> Add filter flag for machine-list and machine-template-list

tsuru/installer/installer.go
This looks like isn't needed anymore and it may be messing the service
startup process by killing docker and leaving partially created
resources behind.
=> installer: remove hacky docker restart during install

Gopkg.lock, Gopkg.toml, tsuru/installer/compose.go, tsuru/installer/dm/drivers.go, tsuru/installer/dm/drivers_test.go, tsuru/installer/install.go, tsuru/installer/install_test.go, vendor/github.com/docker/machine/drivers/amazonec2/amazonec2.go, vendor/github.com/docker/machine/drivers/azure/azureutil/azureutil.go
* aws: allow traffic between service-group instances by default
* google: set private-interface-ip to ens4 by default
* moves compose.yml from /tmp to /etc/tsuru to prevent the file be removed after restart.
=> Update docker-machine vendor and fix some issues

tsuru/client/apps.go, tsuru/client/apps_test.go
=> show related kubernetes-services in app-info

tsuru/admin/iaas.go, tsuru/admin/iaas_test.go
List machine templates and machine iaas ids like `-q` flag already present on node list
=> admin/machine: add flags for list template name and machine id/name only

go.mod, go.sum, tsuru/admin/cluster.go, tsuru/admin/cluster_test.go, tsuru/client/build.go, tsuru/client/init.go, tsuru/client/permission.go, tsuru/client/volume.go, vendor/github.com/tsuru/go-tsuruclient/pkg/tsuru/api_cluster.go, vendor/github.com/tsuru/go-tsuruclient/pkg/tsuru/api_pool.go, vendor/github.com/tsuru/go-tsuruclient/pkg/tsuru/model_env.go
This PR uses the PR #139 as base and improves the error handling as well as the "--default" option to allow three states: unchanged (empty string), true or false.
=> Support to update only certain fields of Cluster (no need to submit all attributes)

tsuru/client/build.go
With this PR the comman `tsuru app-build` will accept `-f/--file-only` tag like `app-deploy`
=> client/build: add file-only tag

tsuru/client/services.go, tsuru/client/services_test.go
Client implementation to https://github.com/tsuru/tsuru/pull/2409.
=> feat(services): show and update plan parameters

tsuru/admin/app_test.go, tsuru/admin/autoscale_test.go, tsuru/admin/broker_test.go, tsuru/admin/cluster_test.go, tsuru/admin/event_test.go, tsuru/admin/iaas_test.go, tsuru/admin/node_test.go, tsuru/admin/nodecontainer_test.go, tsuru/admin/plan_test.go, tsuru/admin/platform_test.go, tsuru/admin/pool_test.go, tsuru/admin/quota_test.go, tsuru/client/auth_test.go, tsuru/client/certificate_test.go, tsuru/client/event_test.go, tsuru/client/permission_test.go, tsuru/client/router_test.go, tsuru/client/services_test.go, tsuru/client/tag_test.go, tsuru/client/token_test.go, tsuru/client/volume_test.go, tsuru/client/webhook_test.go
Improve code coverage and enforce a standard for tests (test cmd.Info())
=> Improve code coverage

tsuru/admin/quota.go, tsuru/admin/quota_test.go
add team-quota commands
```
tsuru team-quota-view
tsuru team-quota-change <limit>
```
note: valid after https://github.com/tsuru/tsuru/pull/2562
=> Team quota

tsuru/client/apps.go, tsuru/client/apps_test.go
Example of output:
tsuru app info -a myapp -s
```
Application: myapp
Platform: python
Plan: c1m1
Pool: mypool (docker)
Teams: team (owner), ops
Cluster External Addresses: myapp.globo.com (cname), routeraddr.router.com
Bound Services: service/instance1, service/instance2
Units: 4
+---------+-------+
| Process | Units |
+---------+-------+
| web     | 4     |
+---------+-------+
```
=> Add simplified view for "tsuru app info"
